### ISSUE TITLE
Show detailed help text for !alias add command

### ISSUE THREAD

**Issue by nehayward** [quintilesims/iqvbot#7]
The `!alias add` command is pretty complex in how it allows go-templating within the alias's body. 
We need to have detailed help text so when users run `!alias add -h`, they know which variables are accessible in the template, how to use those variables, and maybe some examples as well. 

It would be nice to have an `EXAMPLES` field in the various commands' help which showed valid examples of a given command w correct params.

As opposed to current behavior:
```
!alias add -h

IQVBOT APP [2:38 PM]
NAME:
   slackbot !alias add - add a new alias

USAGE:
   slackbot !alias add NAME VALUE
```

**Comment by zpatrick** [comment]
I don't think this applies anymore with how aliases have been chagned to work
